-- tests/fixtures/tropics_d091673/ddl_291_tables.sql (lane d091673)
-- The four tables of pantry migration 291 (energylake-pantry @ 0bcb194,
-- migrations/291_tropical_bank.sql, section "2. the tables", COMMENT ON
-- statements removed; sha256 of the section as extracted: 9d327d2cafc89ba1eca2dd497044eda1ab9d1d4d6ad7d0faacf697c7d63606c5),
-- preceded by the one column set of `datasets` the routes read. For the
-- local Postgres the PG tests load the bank into; never applied anywhere else.

CREATE TABLE datasets (
    dataset_code         text PRIMARY KEY,
    lifecycle_status     text,
    refresh_cron         text,
    freshness_mode       text,
    stale_after_override interval,
    enabled              boolean
);

-- 2. the tables ------------------------------------------------------------
CREATE TABLE tropical_storms (
    storm_id    text PRIMARY KEY CHECK (storm_id ~ '^(al|ep|cp)[0-9]{2}[0-9]{4}$'),
    basin       text NOT NULL,
    number      smallint NOT NULL,
    season      smallint NOT NULL,
    status      text NOT NULL CHECK (status IN ('invest', 'active', 'inactive')),
    names       jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(names) = 'array'),
    aliases     jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(aliases) = 'array'),
    first_seen  timestamptz NOT NULL,
    last_seen   timestamptz NOT NULL,
    last_lat    double precision,
    last_lon    double precision,
    created_ts  timestamptz NOT NULL DEFAULT now(),
    updated_ts  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT tropical_storms_id_parts CHECK (
        basin = substr(storm_id, 1, 2) AND number = substr(storm_id, 3, 2)::smallint
        AND season = substr(storm_id, 5, 4)::smallint),
    CONSTRAINT tropical_storms_invest_status CHECK ((number BETWEEN 90 AND 99) = (status = 'invest')),
    CONSTRAINT tropical_storms_seen_order CHECK (first_seen <= last_seen)
);
CREATE INDEX tropical_storms_aliases_gin ON tropical_storms USING gin (aliases jsonb_path_ops);
CREATE INDEX tropical_storms_last_seen ON tropical_storms (last_seen DESC);

CREATE TABLE tropical_file_vintage (
    vintage_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset               text NOT NULL REFERENCES datasets (dataset_code),
    source                text NOT NULL CHECK (source IN ('nhc', 'nhc_ftp', 'ecmwf_aws', 'hafs_aws',
                                                          'gfs_aws', 'parsed')),
    product               text NOT NULL,
    storm_id              text NOT NULL DEFAULT '',
    vintage_key           text NOT NULL,
    status                text NOT NULL CHECK (status IN ('banked', 'pending', 'absent', 'heartbeat')),
    fetch_ts              timestamptz NOT NULL DEFAULT now(),
    issued_ts             timestamptz,
    r2_key                text,
    byte_size             bigint CHECK (byte_size > 0),
    sha256                text CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    source_url            text,
    source_last_modified  timestamptz,
    source_etag           text,
    meta                  jsonb NOT NULL DEFAULT '{}'::jsonb,
    -- When a pending/absent product finally landed (it was re-checked and
    -- banked). The only column the bank ever UPDATEs, and only on rows with no
    -- bytes; banked rows are never touched.
    closed_ts             timestamptz,
    CONSTRAINT tfv_closed_only_missing CHECK (closed_ts IS NULL OR status IN ('pending', 'absent')),
    CONSTRAINT tfv_banked_means_bytes CHECK (
        (status = 'banked') = (r2_key IS NOT NULL AND sha256 IS NOT NULL AND byte_size IS NOT NULL)),
    CONSTRAINT tfv_heartbeat_is_a_poll CHECK ((status = 'heartbeat') = (product = 'heartbeat')),
    CONSTRAINT uniq_tropical_file_vintage UNIQUE NULLS NOT DISTINCT
        (source, product, storm_id, vintage_key, status, sha256)
);
CREATE INDEX tfv_identity ON tropical_file_vintage (source, product, storm_id, vintage_key);
CREATE INDEX tfv_heartbeat ON tropical_file_vintage (fetch_ts DESC) WHERE product = 'heartbeat';
CREATE INDEX tfv_standing_absence ON tropical_file_vintage (fetch_ts DESC)
    WHERE status = 'absent' AND closed_ts IS NULL;

CREATE TABLE tropical_track_points (
    point_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Deferred: a model cycle inserts its points before the storm book is saved
    -- (tc_model_tracks), all inside one transaction.
    storm_id       text NOT NULL CONSTRAINT ttp_storm_fk REFERENCES tropical_storms (storm_id)
                   DEFERRABLE INITIALLY DEFERRED,
    source         text NOT NULL,
    init_ts        timestamptz NOT NULL,
    advisory       text NOT NULL DEFAULT '',
    tau            smallint NOT NULL,
    valid_ts       timestamptz NOT NULL,
    lat            double precision NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lon            double precision NOT NULL CHECK (lon BETWEEN -180 AND 360),
    vmax_kt        real,
    mslp_hpa       real,
    radii          jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(radii) = 'object'),
    stage          text,
    source_r2_key  text,
    inserted_ts    timestamptz NOT NULL DEFAULT now(),
    -- Rule 5: official and deterministic sources ONLY. Ensemble members
    -- (ecmwf_ens, ecmwf_aifs_ens, atcf:AP01..AP30, AC00) cannot be named here.
    CONSTRAINT ttp_official_or_deterministic CHECK (source IN (
        'nhc_official', 'best_track', 'tcvitals', 'ecmwf_ifs', 'ecmwf_aifs', 'hafs_a', 'hafs_b',
        'atcf:OFCL', 'atcf:AVNO', 'atcf:UKX', 'atcf:CMC', 'atcf:NVGM', 'atcf:NGX', 'atcf:HFSA',
        'atcf:HFSB', 'atcf:HWRF', 'atcf:HMON', 'atcf:CTCX', 'atcf:TVCN', 'atcf:IVCN', 'atcf:HCCA',
        'atcf:RVCN', 'atcf:AEMN', 'atcf:CEMN', 'atcf:GDMN', 'atcf:CLP5', 'atcf:OCD5', 'atcf:TCLP')),
    CONSTRAINT ttp_valid_is_init_plus_tau CHECK (valid_ts = init_ts + make_interval(hours => tau)),
    CONSTRAINT uniq_tropical_track_points UNIQUE (storm_id, source, init_ts, advisory, tau)
);
CREATE INDEX ttp_storm_init ON tropical_track_points (storm_id, init_ts DESC);

CREATE TABLE tropical_place_odds (
    odds_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storm_id       text NOT NULL CONSTRAINT tpo_storm_fk REFERENCES tropical_storms (storm_id)
                   DEFERRABLE INITIALLY DEFERRED,
    issued_ts      timestamptz NOT NULL,
    source         text NOT NULL CHECK (source IN ('nhc_pws', 'ecmwf_ens', 'ecmwf_aifs_ens')),
    advisory       text NOT NULL DEFAULT '',
    place_id       text NOT NULL,
    threshold_kt   smallint CHECK (threshold_kt IN (34, 50, 64)),
    radius_km      real CHECK (radius_km > 0),
    window_h       smallint NOT NULL CHECK (window_h > 0),
    kind           text NOT NULL CHECK (kind IN ('cumulative', 'onset')),
    value          real NOT NULL CHECK (value BETWEEN 0 AND 100),
    below_1pct     boolean NOT NULL DEFAULT false,
    n_members      smallint CHECK (n_members > 0),
    scored         boolean NOT NULL DEFAULT false,
    source_r2_key  text,
    inserted_ts    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT tpo_threshold_or_radius CHECK (threshold_kt IS NOT NULL OR radius_km IS NOT NULL),
    -- NHC's WSP is a probability; an ensemble count is a frequency of n members.
    CONSTRAINT tpo_members_iff_ensemble CHECK ((source = 'nhc_pws') = (n_members IS NULL)),
    CONSTRAINT uniq_tropical_place_odds UNIQUE NULLS NOT DISTINCT
        (storm_id, source, issued_ts, place_id, threshold_kt, radius_km, window_h, kind)
);

