"""
Build the hand-built Los Angeles heat-wave NWS bodies (d091546, D-09-25-76).

    python scripts/build_nws_la_heat_fixture.py          # writes the bodies
    python scripts/build_nws_la_heat_fixture.py --check  # exit 1 if one is stale

d091537's STOP-W: on production, 2026-10-01, Los Angeles (34.052, -118.244)
under an Extreme Heat Watch printed `unknown` on six of nine daily rows, because
NWS's icon token was `hot` and `hot` is deliberately not in the house table.
api.weather.gov is refused by this build session's egress policy (as it was on
2026-09-25, tests/fixtures/nws/README.md), so the body that page read cannot be
recorded here. These are HAND-BUILT to the published schema, shaped like that
morning: six `hot` day periods out of nine, each with NWS's phrase in
`shortForecast`. Every file carries `_provenance` saying so. The gridpoint
(LOX/155,45) and station (KCQT) are the shape of the answer, not a recording.

Outputs, in tests/fixtures/nws/la_heat/:
    points.json  stations.json  latest.json  alerts.json
    forecast.us.json  forecastHourly.us.json
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

OUT = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "nws" / "la_heat"
PT = ZoneInfo("America/Los_Angeles")
LAT, LON = 34.052, -118.244
GRID = "LOX/155,45"
GRID_URL = f"https://api.weather.gov/gridpoints/{GRID}"
ICON = "https://api.weather.gov/icons/land/{dn}/{tok}?size=medium"
PROV = ("Hand-built to the api.weather.gov response schema for Los Angeles "
        "(34.052,-118.244) under the 2026-10-01 Extreme Heat Watch, not recorded: "
        "api.weather.gov was unreachable from the build session (egress policy). "
        "Generated by scripts/build_nws_la_heat_fixture.py (d091546).")
ISSUED = "2026-10-01T12:58:00+00:00"
GENERATED = "2026-10-01T13:10:00+00:00"

# (day name, hi °F, day icon path, day phrase, night name, lo °F, night icon, night phrase)
DAYS = [
    ("Today", 98, "hot", "Hot", "Tonight", 72, "few", "Mostly Clear"),
    ("Thursday", 101, "hot", "Hot", "Thursday Night", 74, "few", "Mostly Clear"),
    ("Friday", 103, "hot", "Hot", "Friday Night", 75, "skc", "Clear"),
    ("Saturday", 100, "hot", "Hot", "Saturday Night", 73, "few", "Mostly Clear"),
    ("Sunday", 94, "few/tsra_hi,20", "Sunny then Slight Chance Showers And Thunderstorms",
     "Sunday Night", 70, "tsra_hi,20", "Slight Chance Showers And Thunderstorms"),
    ("Monday", 97, "hot", "Hot", "Monday Night", 71, "few", "Mostly Clear"),
    ("Tuesday", 95, "hot", "Hot", "Tuesday Night", 69, "few", "Mostly Clear"),
    ("Wednesday", 90, "few", "Mostly Sunny", "Wednesday Night", 66, "few", "Mostly Clear"),
    ("Thursday", 86, "skc", "Sunny", "Thursday Night", 64, "skc", "Clear"),
]
START = datetime(2026, 10, 1, 6, 0, tzinfo=PT)


def _period(n, name, start, end, day, temp, tok, phrase, pop=None):
    return {
        "number": n, "name": name,
        "startTime": start.isoformat(), "endTime": end.isoformat(),
        "isDaytime": day, "temperature": temp, "temperatureUnit": "F",
        "temperatureTrend": "",
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": pop},
        "windSpeed": "5 to 10 mph", "windDirection": "SW",
        "icon": ICON.format(dn="day" if day else "night", tok=tok),
        "shortForecast": phrase, "detailedForecast": "",
    }


def forecast() -> dict:
    periods = []
    for i, (dn, hi, dtok, dph, nn, lo, ntok, nph) in enumerate(DAYS):
        d0 = START + timedelta(days=i)
        day_start = d0 if i == 0 else d0.replace(hour=6)
        dusk = d0.replace(hour=18)
        dawn = (d0 + timedelta(days=1)).replace(hour=6)
        pop = 20 if "tsra" in dtok else 0
        periods.append(_period(2 * i + 1, dn, day_start, dusk, True, hi, dtok, dph, pop))
        periods.append(_period(2 * i + 2, nn, dusk, dawn, False, lo, ntok, nph,
                               20 if "tsra" in ntok else 0))
    return {"_provenance": PROV, "type": "Feature",
            "properties": {"units": "us", "forecastGenerator": "BaselineForecastGenerator",
                           "generatedAt": GENERATED, "updateTime": ISSUED,
                           "periods": periods}}


def hourly() -> dict:
    periods = []
    for h in range(48):
        t0 = START + timedelta(hours=h)
        day_i = (t0.date() - START.date()).days
        day = 6 <= t0.hour < 18
        hot_day = DAYS[day_i][2] == "hot"
        if day and hot_day and 11 <= t0.hour < 18:
            tok, phrase = "hot", "Hot"
        elif day:
            tok, phrase = "skc", "Sunny"
        else:
            tok, phrase = "few", "Mostly Clear"
        hi, lo = DAYS[day_i][1], DAYS[day_i][5]
        frac = max(0.0, 1 - abs(t0.hour - 15) / 9)
        temp = round(lo + (hi - lo) * frac)
        p = _period(h + 1, "", t0, t0 + timedelta(hours=1), day, temp, tok, phrase, 0)
        p["windSpeed"] = "7 mph"
        p["dewpoint"] = {"unitCode": "wmoUnit:degC", "value": 8.3}
        p["relativeHumidity"] = {"unitCode": "wmoUnit:percent", "value": 18}
        p["icon"] = p["icon"].replace("medium", "small")
        periods.append(p)
    return {"_provenance": PROV, "type": "Feature",
            "properties": {"units": "us", "forecastGenerator": "HourlyForecastGenerator",
                           "generatedAt": GENERATED, "updateTime": ISSUED,
                           "validTimes": "2026-10-01T13:00:00+00:00/P7DT11H",
                           "periods": periods}}


def points() -> dict:
    return {"_provenance": PROV, "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [LON, LAT]},
            "properties": {
                "@id": f"https://api.weather.gov/points/{LAT},{LON}",
                "cwa": "LOX", "gridId": "LOX", "gridX": 155, "gridY": 45,
                "forecast": f"{GRID_URL}/forecast",
                "forecastHourly": f"{GRID_URL}/forecast/hourly",
                "forecastGridData": GRID_URL,
                "observationStations": f"{GRID_URL}/stations",
                "timeZone": "America/Los_Angeles", "radarStation": "KSOX"}}


def stations() -> dict:
    return {"_provenance": PROV, "type": "FeatureCollection",
            "features": [{"type": "Feature",
                          "properties": {"stationIdentifier": "KCQT",
                                         "name": "Los Angeles / USC Campus Downtown"}}]}


def latest() -> dict:
    q = lambda unit, v: {"unitCode": unit, "value": v, "qualityControl": "V"}  # noqa: E731
    return {"_provenance": PROV, "type": "Feature",
            "properties": {
                "station": "https://api.weather.gov/stations/KCQT",
                "timestamp": "2026-10-01T12:53:00+00:00",
                "textDescription": "Clear",
                "icon": "https://api.weather.gov/icons/land/night/skc?size=medium",
                "temperature": q("wmoUnit:degC", 23.9),
                "dewpoint": q("wmoUnit:degC", 8.3),
                "windDirection": q("wmoUnit:degree_(angle)", 230),
                "windSpeed": q("wmoUnit:km_h-1", 5.4),
                "windGust": q("wmoUnit:km_h-1", None),
                "seaLevelPressure": q("wmoUnit:Pa", 101220),
                "relativeHumidity": q("wmoUnit:percent", 37.0),
                "heatIndex": q("wmoUnit:degC", None),
                "windChill": q("wmoUnit:degC", None),
                "cloudLayers": [{"base": {"unitCode": "wmoUnit:m", "value": None},
                                 "amount": "CLR"}]}}


def alerts() -> dict:
    return {"_provenance": PROV, "type": "FeatureCollection",
            "features": [{"id": "urn:oid:2.49.0.1.840.0.d091546.heat.1",
                          "properties": {
                              "id": "urn:oid:2.49.0.1.840.0.d091546.heat.1",
                              "event": "Extreme Heat Watch", "severity": "Severe",
                              "headline": "Extreme Heat Watch issued October 1 at 5:58AM "
                                          "PDT until October 5 at 8:00PM PDT by NWS Los "
                                          "Angeles/Oxnard CA",
                              "onset": "2026-10-02T10:00:00-07:00",
                              "ends": "2026-10-05T20:00:00-07:00"}}]}


FILES = {"points.json": points, "stations.json": stations, "latest.json": latest,
         "alerts.json": alerts, "forecast.us.json": forecast,
         "forecastHourly.us.json": hourly}


def _text(fn) -> str:
    return json.dumps(fn(), indent=1, ensure_ascii=False) + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    OUT.mkdir(parents=True, exist_ok=True)
    stale = []
    for name, fn in FILES.items():
        path, want = OUT / name, _text(fn)
        if check:
            if not path.exists() or path.read_text() != want:
                stale.append(name)
        else:
            path.write_text(want)
    if stale:
        print("stale:", ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
