"""
Build the US-unit twins of the hand-built NWS forecast fixtures (d091488 §2.3).

    python scripts/build_nws_us_fixtures.py          # writes the twins
    python scripts/build_nws_us_fixtures.py --check  # exit 1 if a twin is stale

D-09-25-16 moved the NWS arm to `units=us`. The fixtures in `tests/fixtures/nws/`
are hand-built (api.weather.gov was unreachable from the build session), so the
twins are DERIVED from them here rather than typed beside them:

    forecast.json        → forecast.us.json
    forecastHourly.json  → forecastHourly.us.json

Per period, only what `units=us` changes on NWS's side is rewritten:
  - `temperature` in °C → integer °F exactly as NWS prints it (°C · 9/5 + 32,
    rounded half away from zero), `temperatureUnit` "F";
  - `windSpeed` / `windGust` strings in km/h → integer mph, the same rounding;
  - `properties.units` "us".
A period already in °F / mph passes through unchanged. QuantitativeValues
(`dewpoint`, `relativeHumidity`, `probabilityOfPrecipitation`) carry their own
`unitCode` and are left as they are. The provenance stays `hand-built`.
"""

from __future__ import annotations

import json
import math
import re
import sys
from pathlib import Path

FIX = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "nws"
PAIRS = (("forecast.json", "forecast.us.json"),
         ("forecastHourly.json", "forecastHourly.us.json"))
KMH_PER_MPH = 1.609344


def round_half_away(x: float) -> int:
    return int(math.copysign(math.floor(abs(x) + 0.5), x))


def c_to_f(c: float) -> int:
    return round_half_away(c * 9.0 / 5.0 + 32.0)


def _speed_us(s: str) -> str:
    """`"9 km/h"` → `"6 mph"`, `"10 to 20 km/h"` → `"6 to 12 mph"`; mph passes."""
    parts = s.split()
    if not parts or parts[-1] not in ("km/h", "km_h-1"):
        return s
    return re.sub(r"\d+(?:\.\d+)?",
                  lambda m: str(round_half_away(float(m[0]) / KMH_PER_MPH)),
                  " ".join(parts[:-1])) + " mph"


def twin(doc: dict, src_name: str) -> dict:
    out = json.loads(json.dumps(doc))
    out["_provenance"] = (
        f"hand-built US-unit twin of {src_name}, generated by "
        f"scripts/build_nws_us_fixtures.py (°C → integer °F, km/h → integer mph, "
        f"rounded half away from zero). Source provenance: {doc.get('_provenance', '')}")
    props = out["properties"]
    props["units"] = "us"
    for p in props["periods"]:
        if p.get("temperatureUnit") == "C" and p.get("temperature") is not None:
            p["temperature"] = c_to_f(float(p["temperature"]))
            p["temperatureUnit"] = "F"
        for k in ("windSpeed", "windGust"):
            if isinstance(p.get(k), str):
                p[k] = _speed_us(p[k])
    return out


def render(doc: dict) -> str:
    return json.dumps(doc, indent=1, ensure_ascii=False) + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale = []
    for src, dst in PAIRS:
        text = render(twin(json.loads((FIX / src).read_text()), src))
        path = FIX / dst
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(dst)
        else:
            path.write_text(text)
            print(f"wrote {path.relative_to(FIX.parent.parent.parent)}")
    if stale:
        print(f"stale twins: {stale} — rerun scripts/build_nws_us_fixtures.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
